# This file configures the workflows to trigger in our Prow jobs.
# see kubeflow/testing/py/run_e2e_workflow.py
python_paths:
  # Need to place kubeflow/testing in front of kubeflow/kubeflow so that the
  # package can be correctly located.
  - kubeflow/testing/py
  - kubeflow/kubeflow/py
workflows:
  # Run unittests for the shared frontend code
  - py_func: kubeflow.kubeflow.ci.shared_ui_tests.create_workflow
    name: shared-ui-tests
    job_types:
      - presubmit
    include_dirs:
      - components/crud-web-apps/common/frontend/kubeflow-common-lib/*
    kwargs: {}
  # Image Auto Release workflows.
  # The workflows below are related to auto building our Docker images.
  # We have separate pre/postsubmit jobs because we want to use different
  # registries
  #- app_dir: kubeflow/kubeflow/components/tensorflow-notebook-image/releaser
  #  component: workflows
  #  name: tf-notebook-release
  #  job_types:
  #    - presubmit
  #  params:
  #    registry: "gcr.io/kubeflow-ci"
  #    step_image: "gcr.io/kubeflow-ci/test-worker/test-worker:v20190116-b7abb8d-e3b0c4"
  #  include_dirs:
  #    - components/tensorflow-notebook-image/*
