# This file configures the workflows to trigger in our Prow jobs.
# see kubeflow/testing/py/run_e2e_workflow.py
python_paths:
  - kubeflow/kubeflow/py
workflows: []
  # Run unittests
  # TODO(jlewi): Need to add step to run go and python unittests
  # - app_dir: kubeflow/kubeflow/testing/workflows
  #   component: unit_tests
  #   name: unittests
  #   params:
  #     workflowName: unittest
  # Image Auto Release workflows.
  # The workflows below are related to auto building our Docker images.
  # We have separate pre/postsubmit jobs because we want to use different
  # registries
  #- app_dir: kubeflow/kubeflow/components/tensorflow-notebook-image/releaser
  #  component: workflows
  #  name: tf-notebook-release
  #  job_types:
  #    - presubmit
  #  params:
  #    registry: "gcr.io/kubeflow-ci"
  #    step_image: "gcr.io/kubeflow-ci/test-worker/test-worker:v20190116-b7abb8d-e3b0c4"
  #  include_dirs:
  #    - components/tensorflow-notebook-image/*
