# This file configures the workflows to trigger in our Prow jobs.
# see kubeflow/testing/py/run_e2e_workflow.py
workflows:
  - app_dir: kubeflow/kubeflow/testing/workflows
    component: workflows
    name: kubeflow-e2e

  - app_dir: kubeflow/kubeflow/components/k8s-model-server/images/releaser
    component: workflows
    name: tf-serving-image

