apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
namePrefix: tensorboards-web-app-
namespace: kubeflow
commonLabels:
  app: tensorboards-web-app
  kustomize.component: tensorboards-web-app
images:
- name: public.ecr.aws/j1r0q0g6/notebooks/tensorboards-web-app
  newName: public.ecr.aws/j1r0q0g6/notebooks/tensorboards-web-app
  newTag: v1.3.0-rc.1
# We need the name to be unique without the suffix because the original name is what
# gets used with patches
configMapGenerator:
- envs:
  - params.env
  name: parameters
vars:
- fieldref:
    fieldPath: data.TWA_CLUSTER_DOMAIN
  name: TWA_CLUSTER_DOMAIN
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
- fieldref:
    fieldPath: metadata.namespace
  name: TWA_NAMESPACE
  objref:
    apiVersion: v1
    kind: Service
    name: service
- fieldref:
    fieldPath: data.TWA_USERID_HEADER
  name: TWA_USERID_HEADER
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
- fieldref:
    fieldPath: data.TWA_USERID_PREFIX
  name: TWA_USERID_PREFIX
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
- fieldref:
    fieldPath: data.TWA_PREFIX
  name: TWA_PREFIX
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
