# Just for local test
appAddress: http://localhost:8080
defaultApp:
  components:
  - name: metacontroller
    prototype: metacontroller
  - name: jupyter
    prototype: jupyter
  - name: ambassador
    prototype: ambassador
  - name: centraldashboard
    prototype: centraldashboard
  - name: tf-job-operator
    prototype: tf-job-operator
  - name: cloud-endpoints
    prototype: cloud-endpoints
  - name: cert-manager
    prototype: cert-manager
  - name: iap-ingress
    prototype: iap-ingress
  - name: pytorch-operator
    prototype: pytorch-operator
  - name: argo
    prototype: argo
  - name: katib
    prototype: katib
  - name: pipeline
    prototype: pipeline
  parameters:
  - component: cloud-endpoints
    name: secretName
    value: admin-gcp-sa
  - component: cert-manager
    name: acmeEmail
    # TODO: use your email for ssl cert
    value: johnDoe@acme.com
  - component: iap-ingress
    name: ipName
    # TODO: make sure value of ipName is the same as property <ipName>.
    value: ipName
  - component: iap-ingress
    name: hostname
    # TODO: replace with Name of GCP project. This is fully qualified domain name to use with ingress.
    value: kubeflow.endpoints.<Project>.cloud.goog
  - component: jupyter
    name: jupyterHubAuthenticator
    value: iap
  - component: jupyter
    name: platform
    value: gke
  - component: ambassador
    name: platform
    value: gke
  registries:
  - name: kubeflow
    repo: https://github.com/kubeflow/kubeflow
    # default leave empty
    version:
    path: kubeflow
