# Source: https://github.com/tensorflow/k8s/blob/master/tf-job-operator-chart/templates/deployment.yaml

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tf-job-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: tf-job-operator
    spec:
{{- if .Values.rbac.install }}
      serviceAccountName: tf-job-operator
{{- end }}
      containers:
      - name: tf-job-operator
        image: "{{ .Values.tfjob.image }}:{{ .Values.tfjob.tag }}"
        imagePullPolicy: {{ default "" .Values.tfjob.pullPolicy | quote }}
        command:
          - /opt/mlkube/tf_operator
          {{- if .Values.config.configmap }}
          - --controller_config_file={{ .Values.config.file }}
          {{- else if .Values.cloud }}
          - --controller_config_file=/etc/config/controller_config_file.yaml
          {{- end }}
          - -alsologtostderr
          - -v=1
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      {{- if .Values.config.configmap }}
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.config.configmap }}
      {{- else if .Values.cloud  }}
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: tf-job-operator-config
      {{- end }}
