apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: volumes-web-app
        image: docker.io/kubeflownotebookswg/volumes-web-app
        ports:
        - containerPort: 5000
        env:
        - name: APP_PREFIX
          value: $(VWA_PREFIX)
        - name: USERID_HEADER
          value: $(VWA_USERID_HEADER)
        - name: USERID_PREFIX
          value: $(VWA_USERID_PREFIX)
        - name: APP_SECURE_COOKIES
          value: $(VWA_APP_SECURE_COOKIES)
        - name: VOLUME_VIEWER_IMAGE
          value: filebrowser/filebrowser:v2.25.0
        volumeMounts: 
        - name: viewer-spec
          mountPath: /etc/config/viewer-spec.yaml
          subPath: viewer-spec.yaml 
      serviceAccountName: service-account
      volumes: 
      - name: viewer-spec
        configMap: 
          name: viewer-spec
