apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- deployment.yaml
configMapGenerator:
- name: parameters
  envs:
  - params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: project
  objref:
    kind: ConfigMap
    name: parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.project
configurations:
- params.yaml
images:
- name: gcr.io/$(project)/profile-controller
  newName: gcr.io/$(project)/profile-controller
  newTag: latest
