# This rule is not used by the project tensorboard-test itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over tensorboard.test.tensorboards.test.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tensorboard-test
    app.kubernetes.io/managed-by: kustomize
  name: tensorboard-admin-role
rules:
- apiGroups:
  - tensorboard.test.tensorboards.test
  resources:
  - tensorboards
  verbs:
  - '*'
- apiGroups:
  - tensorboard.test.tensorboards.test
  resources:
  - tensorboards/status
  verbs:
  - get
