# This rule is not used by the project tensorboard-test itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to tensorboard.test.tensorboards.test resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tensorboard-test
    app.kubernetes.io/managed-by: kustomize
  name: tensorboard-viewer-role
rules:
- apiGroups:
  - tensorboard.test.tensorboards.test
  resources:
  - tensorboards
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tensorboard.test.tensorboards.test
  resources:
  - tensorboards/status
  verbs:
  - get
