
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: tensorboards.tensorboard.kubeflow.org
spec:
  group: tensorboard.kubeflow.org
  names:
    kind: Tensorboard
    listKind: TensorboardList
    plural: tensorboards
    singular: tensorboard
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Tensorboard is the Schema for the tensorboards API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: TensorboardSpec defines the desired state of Tensorboard
          properties:
            logspath:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "make" to regenerate code after modifying this file'
              type: string
          required:
          - logspath
          type: object
        status:
          description: TensorboardStatus defines the observed state of Tensorboard
          properties:
            conditions:
              description: Conditions is an array of current conditions
              items:
                description: TensorboardCondition defines the observed state of Tensorboard
                properties:
                  deploymentState:
                    description: Deployment status, 'Available', 'Progressing', 'ReplicaFailure'
                      .
                    type: string
                  lastProbeTime:
                    description: Last time we probed the condition.
                    format: date-time
                    type: string
                required:
                - deploymentState
                type: object
              type: array
            readyReplicas:
              description: ReadyReplicas defines the number of Tensorboard Servers
                that are available to connect. The value of ReadyReplicas can be either
                0 or 1
              format: int32
              type: integer
          required:
          - conditions
          - readyReplicas
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
