apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- virtual-service.yaml
namespace: kubeflow
commonLabels:
  app: secrets-web-app
  kustomize.component: secrets-web-app
configurations:
- params.yaml
