apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: profiles-
commonLabels:
  kustomize.component: profiles
images:
- name: gcr.io/kubeflow-images-public/kfam
  newName: gcr.io/kubeflow-images-public/kfam
  newTag: vmaster-g9f3bfd00
- name: gcr.io/kubeflow-images-public/profile-controller
  newName: gcr.io/kubeflow-images-public/profile-controller
  newTag: vmaster-ga49f658f
resources:
- ../base/cluster-role-binding.yaml
- ../base/crd.yaml
- ../base/deployment.yaml
- ../base/service.yaml
- ../base/service-account.yaml
- ../overlays/istio/virtual-service.yaml
- ../overlays/application/application.yaml
patchesStrategicMerge:
- deployment_patch.yaml
configMapGenerator:
# We need the name to be unique without the suffix because the original name is what
# gets used with patches
- name: profiles-config
  literals:
  - admin=
  - gcp-sa=
