---
apiVersion: kubeflow.org/v1beta1
kind: Notebook
metadata:
  name: notebook-sample-v1beta1
spec:
  template:
    spec:
      containers:
        - name: notebook-sample-v1
          image: docker.io/kubeflownotebookswg/notebook-servers/jupyter:v1.5.0-rc.1
