apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- ../../base
- service.yaml
- virtual-service.yaml
- authorizationpolicy.yaml

commonLabels:
  kustomize.component: profiles

patchesStrategicMerge:
- patches/kfam.yaml
- patches/remove-namespace.yaml

configurations:
- params.yaml

vars:
- name: PROFILES_NAMESPACE
  fieldref:
    fieldpath: metadata.namespace
  objref:
    name: profiles-kfam
    kind: Service
    apiVersion: v1

images:
- name: docker.io/kubeflownotebookswg/kfam
  newName: docker.io/kubeflownotebookswg/kfam
  newTag: v1.7.0-rc.0
