apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: notebook-controller
  kustomize.component: notebook-controller
configMapGenerator:
- literals:
  - USE_ISTIO=true
  - ISTIO_GATEWAY=kubeflow/kubeflow-gateway
  name: notebook-controller-config
images:
- name: gcr.io/kubeflow-images-public/notebook-controller
  newName: gcr.io/kubeflow-images-public/notebook-controller
  newTag: vmaster-g6eb007d0
kind: Kustomization
namePrefix: notebook-controller-
namespace: kubeflow
patchesStrategicMerge:
- deployment_patch.yaml
resources:
- ../base/cluster-role-binding.yaml
- ../base/cluster-role.yaml
- ../base/crd.yaml
- ../base/deployment.yaml
- ../base/service-account.yaml
- ../base/service.yaml
- ../overlays/application/application.yaml
