name: CentralDashboard-angular Frontend check
on:
  pull_request:
    paths:
      - components/centraldashboard-angular/frontend/**

jobs:
  run-frontend-unittests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Run unit tests
        run: |
          cd components/centraldashboard-angular/frontend/
          npm i
          npm run test:prod

  run-frontend-format-check:
    name: Format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Run format:check
        run: |
          cd components/centraldashboard-angular/frontend/
          npm i
          npm run format:check