# This workflow will build and push Docker images and will log in to a Docker registry if required.
# For more information see: https://github.com/docker/build-push-action

name: profile controller - Build and push Docker image

on:
  push:
    branches:
      - v0.3.0-kubeflow-v1.3-branch
    paths:
      - components/profile-controller/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout üõéÔ∏è
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push üîß
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: docker.io/platiagro/profile-controller:v1.3.0
        context: components/profile-controller/

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
