name: Frontend Lint
on:
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - components/crud-web-apps/common/frontend/**
      - components/crud-web-apps/jupyter/frontend/**
      - components/crud-web-apps/tensorboards/frontend/**
      - components/crud-web-apps/volumes/frontend/**

jobs:
  lint:
    name: Lint frontend code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.13
    - name: Lint common
      run: |
        cd components/crud-web-apps/common/frontend/kubeflow-common-lib
        npm i
        npm run lint
    - name: Lint jupyter
      run: |
        cd components/crud-web-apps/jupyter/frontend
        npm i
        npm run lint
    - name: Lint tensorboards
      run: |
        cd components/crud-web-apps/tensorboards/frontend
        npm i
        npm run lint
    - name: Lint volumes
      run: |
        cd components/crud-web-apps/volumes/frontend
        npm i
        npm run lint
