name: Build JWA manifests
on:
  pull_request:
    paths:
      - components/crud-web-apps/jupyter/**
      - components/crud-web-apps/common/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install kustomize
      run: |
        curl --silent --location --remote-name "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v3.2.3/kustomize_kustomize.v3.2.3_linux_amd64"
        chmod a+x kustomize_kustomize.v3.2.3_linux_amd64
        sudo mv kustomize_kustomize.v3.2.3_linux_amd64 /usr/local/bin/kustomize

    - name: Build manifests
      run: |
        cd components/crud-web-apps/jupyter/manifests
        kustomize build overlays/istio
