name: JWA Intergration Test
on:
  pull_request:
    paths:
      - components/crud-web-apps/jupyter/**
      - components/crud-web-apps/common/**
    branches:
      - master
      - v*-branch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.number }}
  cancel-in-progress: true

env:
  IMG: jupyter-web-app
  TAG: intergration-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build JWA Image 
      run: |
        cd components/crud-web-apps/jupyter
        ARCH=linux/ppc64le make docker-build-multi-arch
        ARCH=linux/amd64 make docker-build-multi-arch 

    - name: Install KinD
      run: ./components/testing/gh-actions/install_kind.sh

    - name: Create KinD Cluster
      run: kind create cluster --config components/testing/gh-actions/kind-1-25.yaml

    - name: Load Image into KinD Cluster 
      run: |
        kind load docker-image "${IMG}:${TAG}"

    - name: Install kustomize
      run: ./components/testing/gh-actions/install_kustomize.sh

    - name: Install Istio
      run: ./components/testing/gh-actions/install_istio.sh

    - name: Build & Apply manifests
      run: |
        cd components/crud-web-apps/jupyter/manifests
        kubectl create ns kubeflow

        export CURRENT_JWA_IMG=docker.io/kubeflownotebookswg/jupyter-web-app:latest
        export PR_JWA_IMG="${IMG}:${TAG}"

        kustomize build overlays/istio | sed "s#$CURRENT_JWA_IMG#$PR_JWA_IMG#g" | kubectl apply -f -
        kubectl wait pods -n kubeflow -l app=jupyter-web-app --for=condition=Ready --timeout=300s
