name: Build & Publish Notebook Controller Docker image
on:
  push:
    branches:
      - master
      - v*-branch
    paths:
      - components/notebook-controller/**
      - components/common/**
      - releasing/version/VERSION

env:
  DOCKER_USER: kubeflow
  IMG: ghcr.io/kubeflow/kubeflow/notebook-controller
  ARCH: linux/amd64,linux/ppc64le,linux/arm64/v8

jobs:
  push_to_registry:
    name: Build & Push Docker image to GHCR
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: dorny/paths-filter@v3
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          version:
            - 'releasing/version/VERSION'

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
      with:
        # see: https://github.com/tonistiigi/binfmt/issues/215
        # see: https://github.com/docker/setup-qemu-action/issues/198
        image: tonistiigi/binfmt:qemu-v7.0.0-28

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push multi-arch docker image
      run: |
        cd components/notebook-controller
        ARCH=linux/amd64 make docker-build-multi-arch
        ARCH=linux/ppc64le make docker-build-multi-arch
        ARCH=linux/arm64/v8 make docker-build-multi-arch
        make docker-build-push-multi-arch

    - name: Build and push latest multi-arch docker image
      if: github.ref == 'refs/heads/master'
      run: |
        export TAG=latest
        cd components/notebook-controller
        make docker-build-push-multi-arch

    - name: Build and push multi-arch docker image on Version change
      id: version
      if: steps.filter.outputs.version == 'true'
      run: |
        export TAG=$(cat releasing/version/VERSION)
        cd components/notebook-controller
        make docker-build-push-multi-arch
