name: Build & Publish Notebook Controller Docker image
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - v*-branch
    paths:
      - components/notebook-controller/**
      - components/common/**
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - components/notebook-controller/**
      - components/common/**

env:
  DOCKER_USER: kubeflownotebookswg

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.KUBEFLOWNOTEBOOKSWG_DOCKER_TOKEN }}

      - name: export env vars
        run: |
          cd components/notebook-controller
          export IMAGE_NAME=notebook-controller
          export IMAGE_ID="$DOCKER_USER/$IMAGE_NAME"
          echo IMAGE_ID=$IMAGE_ID >> $GITHUB_ENV
          echo COMPONENT_PATH=$PWD >> $GITHUB_ENV
          echo IMAGE_TAG=$(git describe --tags --always --dirty) >> $GITHUB_ENV

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ppc64le

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/ppc64le
          context: ./components
          file: ${{ env.COMPONENT_PATH }}/Dockerfile
          push: ${{ contains(fromJson('["push", "workflow_dispatch"]'), github.event_name) }}
          tags: ${{ env.IMAGE_ID }}:${{ env.IMAGE_TAG }}
