name: Build & Publish base Notebook Server Docker images
on:
  push:
    branches:
      - master
      - v*-branch
    paths:
      - components/example-notebook-servers/base/**
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - components/example-notebook-servers/base/**

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to DockerHub
      if: github.event_name == 'push'
      uses: docker/login-action@v2
      with:
        username: kubeflownotebookswg
        password: ${{ secrets.KUBEFLOWNOTEBOOKSWG_DOCKER_TOKEN }}

    - name: Build all Notebook Server images via central-Makefile
      run: |
        cd components/example-notebook-servers/
        export TAG=$(git describe --tags --always --dirty)
        make docker-build-all
    
    - name: Push all Notebook Server images via central-Makefile
      if: github.event_name == 'push'
      run: |
        cd components/example-notebook-servers/
        export TAG=$(git describe --tags --always --dirty)
        make docker-push-all
