name: Build & Publish Notebook Server Docker images
on:
  push:
    branches:
      - master
      - v*-branch
    paths:
      - components/example-notebook-servers/**

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Run codeserver-python Notebook Server build and push
      run: |
        cd components/example-notebook-servers/codeserver-python
        export IMG=docker.io/kubeflownotebookswg
        export TAG=$(git describe --tags --always);
        docker build -t ${IMG}:${TAG} -f Dockerfile . 
        docker push ${IMG}:${TAG}

    - name: Run jupyter-scipy Notebook Server build and push
      run: |
        cd components/example-notebook-servers/jupyter-scipy
        export IMG=docker.io/kubeflownotebookswg
        export TAG=$(git describe --tags --always);
        docker build -t ${IMG}:${TAG} -f Dockerfile . 
        docker push ${IMG}:${TAG}

    - name: Run jupyter-pytorch-full Notebook Server build and push
      run: |
        cd components/example-notebook-servers/jupyter-pytorch-full
        export IMG=docker.io/kubeflownotebookswg
        export TAG=$(git describe --tags --always);
        docker build -t ${IMG}:${TAG} -f cpu.Dockerfile . 
        docker push ${IMG}:${TAG}

    - name: Run jupyter-pytorch-full Notebook Server build and push
      run: |
        cd components/example-notebook-servers/jupyter-pytorch-full
        export IMG=docker.io/kubeflownotebookswg
        export TAG=$(git describe --tags --always);
        docker build -t ${IMG}:${TAG} -f cuda.Dockerfile . 
        docker push ${IMG}:${TAG}

    - name: Run jupyter-tensorflow-full Notebook Server build and push
      run: |
        cd components/example-notebook-servers/jupyter-tensorflow-full
        export IMG=docker.io/kubeflownotebookswg
        export TAG=$(git describe --tags --always);
        docker build -t ${IMG}:${TAG} -f cpu.Dockerfile . 
        docker push ${IMG}:${TAG}
        
    - name: Run jupyter-tensorflow-cuda-full Notebook Server build and push
      run: |
        cd components/example-notebook-servers/jupyter-tensorflow-full
        export IMG=docker.io/kubeflownotebookswg
        export TAG=$(git describe --tags --always);
        docker build -t ${IMG}:${TAG} -f cuda.Dockerfile . 
        docker push ${IMG}:${TAG}

    - name: Run rstudio-tidyverse Notebook Server build and push
      run: |
        cd components/example-notebook-servers/rstudio-tidyverse
        export IMG=docker.io/kubeflownotebookswg
        export TAG=$(git describe --tags --always);
        docker build -t ${IMG}:${TAG} -f Dockerfile . 
        docker push ${IMG}:${TAG}
