name: Build & Publish PodDefaults Docker image
on:
  push:
    branches:
      - master
      - v*-branch
    paths:
      - components/admission-webhook/**
      - releasing/version/VERSION

env:
  DOCKER_USER: kubeflownotebookswg
  IMG: kubeflownotebookswg/poddefaults-webhook
  ARCH: linux/ppc64le,linux/amd64

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          version:
            - 'releasing/version/VERSION'

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ secrets.KUBEFLOWNOTEBOOKSWG_DOCKER_TOKEN }}

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push multi-arch docker image
      run: |
        cd components/admission-webhook
        make docker-build-push-multi-arch

    - name: Build and push latest multi-arch docker image
      if: github.ref == 'refs/heads/master'
      run: |
        export TAG=latest
        cd components/admission-webhook
        make docker-build-push-multi-arch

    - name: Build and push multi-arch docker image on Version change
      id: version
      if: steps.filter.outputs.version == 'true'
      run: |
        export TAG=$(cat releasing/version/VERSION)
        cd components/admission-webhook
        make docker-build-push-multi-arch
