name: Build & Publish Profile Controller Docker image
on:
  push:
    branches:
      - master
      - v*-branch
    paths:
      - components/profile-controller/**
      - releasing/version/VERSION
  pull_request:
    branches:
      - master
      - v*-branch
    paths:
      - components/profile-controller/**

jobs:
  push_to_registry:
    name: Build & Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          version:
            - 'releasing/version/VERSION'

    - name: Login to DockerHub
      if: github.event_name == 'push'
      uses: docker/login-action@v2
      with:
        username: kubeflownotebookswg
        password: ${{ secrets.KUBEFLOWNOTEBOOKSWG_DOCKER_TOKEN }}

    - name: Run Profile Controller build
      run: |
        cd components/profile-controller
        export IMG=kubeflownotebookswg/profile-controller
        make docker-build

    - name: Run Profile Controller push
      if: github.event_name == 'push'
      run: |
        cd components/profile-controller
        export IMG=kubeflownotebookswg/profile-controller
        make docker-push

    - name: Run Profile Controller push on Version change
      id: version
      if: github.event_name == 'push' && steps.filter.outputs.version == 'true'
      run: |
        export TAG=$(cat releasing/version/VERSION)
        cd components/profile-controller
        export IMG=kubeflownotebookswg/profile-controller
        make docker-build
        make docker-push
