name: Profiles/KFAM Integration Tests
on:
  pull_request:
    paths:
      - components/profile-controller/**
      - components/access-management/**
    branches:
      - master
      - v*-branch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PROFILE_IMG: profile-controller
  KFAM_IMG: kfam
  TAG: intergration-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Profile Controller Image
      run: |
        TAG=${{env.TAG}}
        cd components/profile-controller
        ARCH=linux/ppc64le make docker-build-multi-arch IMG=${{env.PROFILE_IMG}}
        ARCH=linux/amd64 make docker-build-multi-arch IMG=${{env.PROFILE_IMG}}

    - name: Build Kfam Image
      run: |
        cd components/access-management
        ARCH=linux/ppc64le make docker-build-multi-arch IMG=${{env.KFAM_IMG}}
        ARCH=linux/amd64 make docker-build-multi-arch IMG=${{env.KFAM_IMG}}

    - name: Install KinD
      run: ./components/testing/gh-actions/install_kind.sh

    - name: Create KinD Cluster
      run: kind create cluster --config components/testing/gh-actions/kind-1-25.yaml

    - name: Load Images into KinD Cluster
      run: |
        kind load docker-image ${{env.PROFILE_IMG}}:${{env.TAG}}
        kind load docker-image ${{env.KFAM_IMG}}:${{env.TAG}}

    - name: Install kustomize
      run: ./components/testing/gh-actions/install_kustomize.sh

    - name: Install Istio
      run: ./components/testing/gh-actions/install_istio.sh

    - name: Build & Apply manifests
      run: |
        cd components/profile-controller/config
        kubectl create ns kubeflow

        kustomize build overlays/kubeflow | kubectl apply -f -

        # profiles
        DEPLOYMENT=profiles-deployment
        CONTAINER=manager

        IMG=${{env.PROFILE_IMG}}:${{env.TAG}}
        kubectl patch deployment $DEPLOYMENT -n kubeflow --patch \
          '{"spec": {"template": {"spec": {"containers": [{"name": "'"$CONTAINER"'","image": "'"$IMG"'"}]}}}}'

        # kfam
        CONTAINER=kfam

        IMG=${{env.KFAM_IMG}}:${{env.TAG}}
        kubectl patch deployment $DEPLOYMENT -n kubeflow --patch \
          '{"spec": {"template": {"spec": {"containers": [{"name": "'"$CONTAINER"'","image": "'"$IMG"'"}]}}}}'

        kubectl wait deploy -n kubeflow $DEPLOYMENT --for=jsonpath='{.status.readyReplicas}'=1 --timeout=300s
