name: Build & Apply Profile Controller manifests in KinD
on:
  pull_request:
    paths:
      - components/profile-controller/config/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install KinD
      run: |
        chmod +x components/testing/gh-actions/install_kind.sh
        ./components/testing/gh-actions/install_kind.sh

    - name: Create KinD Cluster
      run: kind create cluster --config components/testing/gh-actions/kind.yaml

    - name: Install kustomize
      run: |
        chmod +x components/testing/gh-actions/install_kustomize.sh
        ./components/testing/gh-actions/install_kustomize.sh

    - name: Install Istio
      run: |
        chmod +x components/testing/gh-actions/install_istio.sh
        ./components/testing/gh-actions/install_istio.sh

    - name: Build & Apply manifests
      run: |
        cd components/profile-controller/config
        kubectl create ns kubeflow
        kustomize build overlays/kubeflow | kubectl apply -f -
