# Define a GitHub action workflow to determine whether issues 
# should be added or removed from the Needs Triage Kanban board.
name: Check Triage Status of Issue
on:
  issues:
    types: [opened, closed, reopened, transferred, labeled, unlabeled]
    # Issue is created, Issue is closed, Issue added or removed from projects, Labels added/removed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Update Kanban
        uses: kubeflow/code-intelligence/Issue_Triage/action@master
        with:
          # Letting input NEEDS_TRIAGE_PROJECT_CARD_ID use the default value
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.triage_projects_github_token }}

