name: VWA Multi-Arch Build Test
on:
  pull_request:
    paths:
      - components/crud-web-apps/volumes/**
      - components/crud-web-apps/common/**
      - releasing/version/VERSION
    branches:
      - master
      - v*-branch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.number }}
  cancel-in-progress: true

env:
  IMG: ghcr.io/kubeflow/kubeflow/volumes-web-app

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build multi-arch Image
      run: |
        cd components/crud-web-apps/volumes
        ARCH=linux/amd64 make docker-build-multi-arch
        ARCH=linux/ppc64le make docker-build-multi-arch
        ARCH=linux/arm64/v8 make docker-build-multi-arch
