name: Build & Publish VWA Docker image
on:
  push:
    branches:
      - master
      - v*-branch
    paths:
      - components/crud-web-apps/volumes/**
      - components/crud-web-apps/common/**
      - releasing/version/VERSION

env:
  IMG: ghcr.io/kubeflow/kubeflow/volumes-web-app
  ARCH: linux/amd64,linux/ppc64le,linux/arm64/v8

jobs:
  push_to_registry:
    name: Build & Push image to GHCR
    if: ${{ github.repository == 'kubeflow/kubeflow' }}
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: dorny/paths-filter@v3
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          version:
            - 'releasing/version/VERSION'

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push multi-arch docker image
      run: |
        cd components/crud-web-apps/volumes
        ARCH=linux/amd64 make docker-build-multi-arch
        ARCH=linux/ppc64le make docker-build-multi-arch
        ARCH=linux/arm64/v8 make docker-build-multi-arch
        make docker-build-push-multi-arch

    - name: Build and push latest multi-arch docker image
      if: github.ref == 'refs/heads/master'
      run: |
        export TAG=latest
        cd components/crud-web-apps/volumes
        make docker-build-push-multi-arch

    - name: Build and push multi-arch docker image on Version change
      id: version
      if: steps.filter.outputs.version == 'true'
      run: |
        export TAG=$(cat releasing/version/VERSION)
        cd components/crud-web-apps/volumes
        make docker-build-push-multi-arch
